# MySQL properties
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/java_2.3.1
db.username=root
db.password=root
db.entity.package = com.qooobico.remindme.server.entity

# Hibernate properties
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

